<html>
<head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="static/SyntaxHighlighter/scripts/shCore.js"></script>
    <script type="text/javascript" src="static/SyntaxHighlighter/scripts/shBrushBash.js"></script>
    <link type="text/css" rel="stylesheet" href="static/SyntaxHighlighter/styles/shCore.css" />
    <link type="text/css" rel="stylesheet" href="static/SyntaxHighlighter/styles/shThemeDefault.css"/>
    <script type="text/javascript" src="static/jquery/jquery.js"></script>
    <link type="text/css" rel="stylesheet" href="static/common.css"/>
</head>
<body>
