<html>
<head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="static/jquery/jquery.js"></script>

    <link type="text/css" rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css"/>
    <script type="text/javascript" src="static/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="static/bootstrap/js/bootstrap-tab.js"></script>

    <link type="text/css" rel="stylesheet" href="static/common.css"/>
</head>
<body>
